// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgU8C3wz1khnqmAvzhaZvfQFx34iIx0ZU',
    appId: '1:458201036128:web:84fa101acd6a5ed246da05',
    messagingSenderId: '458201036128',
    projectId: 'chatapp-c1e4c',
    authDomain: 'chatapp-c1e4c.firebaseapp.com',
    storageBucket: 'chatapp-c1e4c.firebasestorage.app',
    measurementId: 'G-QV46BSQKRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZHFJnxExVx7wxK23yG_YlF8_fdyl3du8',
    appId: '1:458201036128:android:946edea710c384e946da05',
    messagingSenderId: '458201036128',
    projectId: 'chatapp-c1e4c',
    storageBucket: 'chatapp-c1e4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBagkIupIkH3DYP-roHRknKMmtc5ZrSrZU',
    appId: '1:458201036128:ios:04b83f4025e13ce646da05',
    messagingSenderId: '458201036128',
    projectId: 'chatapp-c1e4c',
    storageBucket: 'chatapp-c1e4c.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBagkIupIkH3DYP-roHRknKMmtc5ZrSrZU',
    appId: '1:458201036128:ios:04b83f4025e13ce646da05',
    messagingSenderId: '458201036128',
    projectId: 'chatapp-c1e4c',
    storageBucket: 'chatapp-c1e4c.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgU8C3wz1khnqmAvzhaZvfQFx34iIx0ZU',
    appId: '1:458201036128:web:7bd0c2ca91d63de046da05',
    messagingSenderId: '458201036128',
    projectId: 'chatapp-c1e4c',
    authDomain: 'chatapp-c1e4c.firebaseapp.com',
    storageBucket: 'chatapp-c1e4c.firebasestorage.app',
    measurementId: 'G-3WC4VMW41Y',
  );
}
